In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
2**np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
np.sum(0.1 ** (3 * np.arange(0, 6)) * 0.2 ** (4 * np.arange(0, 6)))

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
a = np.zeros((8, 8))

a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
print(X)

X_radius = np.sqrt(X[:, 0]**2 + X[:, 1]**2)
X_angle = np.arccos(X[:, 0] / X_radius)

X_polar = np.concatenate((X_radius.T, X_angle.T), axis=0)
X_polar

[[0.97785066 0.79798426]
 [0.70281201 0.03397616]
 [0.85045024 0.27988914]
 [0.98046135 0.22666163]
 [0.97358055 0.72651632]]


array([1.26212947, 0.70363279, 0.89532314, 1.00632   , 1.21477778,
       0.68445686, 0.04830556, 0.31794206, 0.22718743, 0.6410848 ])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
print(X)

index = np.unravel_index(np.argmax(X, axis=None), X.shape)
print('Max Value index: {index}, and max value: {value}'.format(index=index, value=X[index]))

[[0.91152071 0.51697211 0.49199587 0.89433597 0.8019388  0.63960914
  0.10691531 0.29668579 0.83221374 0.59936073]
 [0.07631439 0.251492   0.89630663 0.92884967 0.14563376 0.93505981
  0.54952638 0.76666993 0.3147299  0.92838871]
 [0.09642966 0.92566043 0.4022249  0.3601823  0.88302112 0.71213568
  0.6919131  0.62828917 0.99069026 0.21867917]
 [0.93839931 0.11945447 0.24684913 0.24427675 0.63942141 0.17580601
  0.84220425 0.04396784 0.98503824 0.09608568]
 [0.41759371 0.26414994 0.7529564  0.45790818 0.5784893  0.42845843
  0.86117271 0.81483958 0.69082822 0.31397185]
 [0.85293808 0.92920739 0.42419122 0.43533712 0.97657231 0.2485359
  0.75500276 0.03121509 0.13048299 0.01813153]
 [0.67295517 0.10593691 0.47924761 0.55091735 0.38875007 0.68818584
  0.15991547 0.37491041 0.90474764 0.25719323]
 [0.19071809 0.84771034 0.39878786 0.43819833 0.97167364 0.19810667
  0.76024403 0.35788255 0.81278976 0.39279957]
 [0.61694645 0.42398416 0.75031884 0.93536143 0.3315114  0.11323528
  0.72202135 

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

print(X, y)

distances = np.sqrt(np.sum((X - y)**2, axis=1))
index = np.argmin(distances)

print('Closest point: {}'.format(X[index]))

[[0.15763938 0.20961096]
 [0.25837569 0.71037102]
 [0.88949466 0.3738775 ]
 [0.28721722 0.80547614]
 [0.94812673 0.63192208]
 [0.32912348 0.83235615]
 [0.0464926  0.06268564]
 [0.55194864 0.10221541]
 [0.6488241  0.23581986]
 [0.07880925 0.27559077]] [[0.84109192 0.25375909]]
Closest point: [0.88949466 0.3738775 ]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
## your code

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [8]:
X = np.random.random((10, 10))

means = np.mean(X, axis=1)
X - means[:, np.newaxis]

array([[ 0.24677144, -0.06874894, -0.40714397, -0.18339073, -0.32653131,
         0.40428816,  0.21422167,  0.21612906,  0.01235485, -0.10795023],
       [ 0.52734629,  0.42442207, -0.3361017 , -0.1985765 , -0.05563878,
        -0.14232064, -0.20596312, -0.08232317,  0.21198961, -0.14283406],
       [-0.15693053, -0.16072041,  0.04651101,  0.07208634,  0.35668571,
        -0.39675985, -0.09855627,  0.22318591, -0.11050763,  0.22500573],
       [-0.31796563,  0.03415755, -0.22674266,  0.19285535,  0.33557262,
         0.32464831, -0.37450828,  0.21047349, -0.40445447,  0.22596372],
       [ 0.07146784,  0.01845108,  0.12420517, -0.17816407, -0.00356039,
        -0.16331455,  0.09532102,  0.27258004, -0.01615368, -0.22083245],
       [ 0.4542912 , -0.04878286,  0.11736859,  0.229352  ,  0.37581202,
        -0.38589443, -0.22954904, -0.11683955, -0.38153882, -0.0142191 ],
       [ 0.43050009, -0.02820811, -0.40486027,  0.32663729,  0.22999589,
         0.16699159, -0.05339817,  0.13012225

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [9]:
X = np.random.normal(loc=5, scale=2., size=1000)

mean = X.mean()
var = X.var()

print('Mean: {mean}, Variance: {var}'.format(mean=mean, var=var))

Mean: 5.1062464820667826, Variance: 3.851162931051549


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [10]:
np.roll(np.arange(5).T, 2)

array([3, 4, 0, 1, 2])

In [11]:
np.concatenate((np.roll(np.arange(5)[:, np.newaxis], 0).T, 
                np.roll(np.arange(5)[:, np.newaxis], -1).T,
                np.roll(np.arange(5)[:, np.newaxis], -2).T,
                np.roll(np.arange(5)[:, np.newaxis], -3).T,
                np.roll(np.arange(5)[:, np.newaxis], -4).T), axis=0)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [15]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 1, 2, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [ ]:
## your code